refactor: update GitHub Actions workflows for Docker image builds

diff --git a/.github/workflows/build_docker_image_template.yml b/.github/workflows/build_docker_image_template.yml
--- a/.github/workflows/build_docker_image_template.yml
+++ b/.github/workflows/build_docker_image_template.yml
@@ -16,8 +16,10 @@ on:
 jobs:
 
 
-  parse-credentials:
-    runs-on: ubuntu-latest
+  build:
+    strategy:
+        fail-fast: false
+    runs-on: ${{ inputs.runs_on }}
     env:
       env_vars: ${{ secrets.env_vars }}
     outputs:
@@ -34,66 +36,59 @@ jobs:
     - name: Validate credentials
       run: |
         # Secrets are now available as masked environment variable.
-        echo $CREDENTIAL1 # or ${{ env.docker_username }}
-        echo $CREDENTIAL2 # or ${{ env.CREDENTIAL2 }}
+        #echo $CREDENTIAL1 # or ${{ env.docker_username }}
         if [ "${{ env.docker_username }}" != "niteris" ]; then
-          echo "Error: CREDENTIAL1 is not 'niteris'"
+          echo "Error: docker_username is not 'niteris'"
+          exit 1
+        fi
+        #  docker_registry_image=${{ needs.credentials.outputs.registry_image  }}
+        if [ "${{ env.docker_registry_image }}" != "niteris/fastled-wasm" ]; then
+          echo "Error: docker_registry_image is not 'niteris/fastled-wasm'"
           exit 1
         fi
 
 
-  build:
-    needs: parse-credentials
-    runs-on: ${{ inputs.runs_on }}
-    strategy:
-      fail-fast: false
-    steps:
-      - name: Prepare
-        run: |
-          platform=${{ inputs.platform }}
-          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
-      - name: Docker meta
-        id: meta
-        uses: docker/metadata-action@v5
-        with:
-          images: ${{ inputs.registry_image }}
-          tags: |
-            type=raw,value=latest,enable={{is_default_branch}}
-      - name: Debug
-        run: |
-          if [ "${{ needs.parse-credentials.outputs.docker_username }}" != "niteris" ]; then
-            echo "Error: CREDENTIAL1 is not 'niteris'"
-            exit 1
-          fi
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ inputs.docker_username }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
-      - name: Build and push by digest
-        id: build
-        uses: docker/build-push-action@v6
-        with:
-          platforms: ${{ inputs.platform }}
-          context: https://github.com/zackees/fastled-wasm.git
-          file: Dockerfile
-          labels: ${{ steps.meta.outputs.labels }}
-          outputs: type=image,name=${{ inputs.registry_image }},push-by-digest=true,name-canonical=true,push=true
-          build-args: |
-            PLATFORM_TAG=${{ inputs.platform == 'linux/arm64' && '-arm64' || '' }}
+    - name: Prepare
+      run: |
+        platform=${{ inputs.platform }}
+        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
+    - name: Docker meta
+      id: meta
+      uses: docker/metadata-action@v5
+      with:
+        images: ${{ env.registry_image }}
+        tags: |
+          type=raw,value=latest,enable={{is_default_branch}}
+
+    - name: Set up Docker Buildx
+      uses: docker/setup-buildx-action@v3
+    - name: Login to Docker Hub
+      uses: docker/login-action@v3
+      with:
+        username: ${{ env.docker_username }}
+        password: ${{ secrets.DOCKER_PASSWORD }}
+    - name: Build and push by digest
+      id: build
+      uses: docker/build-push-action@v6
+      with:
+        platforms: ${{ inputs.platform }}
+        context: https://github.com/zackees/fastled-wasm.git
+        file: Dockerfile
+        labels: ${{ steps.meta.outputs.labels }}
+        outputs: type=image,name=${{ env.registry_image }},push-by-digest=true,name-canonical=true,push=true
+        build-args: |
+          PLATFORM_TAG=${{ inputs.platform == 'linux/arm64' && '-arm64' || '' }}
           cache-from: type=gha
           cache-to: type=gha,mode=max,compression=zstd
-      - name: Export digest
-        run: |
-          mkdir -p /tmp/digests
-          digest="${{ steps.build.outputs.digest }}"
-          touch "/tmp/digests/${digest#sha256:}"
-      - name: Upload digest
-        uses: actions/upload-artifact@v4
-        with:
-            name: digests-${{ env.PLATFORM_PAIR }}
-            path: /tmp/digests/*
-            if-no-files-found: error
-            retention-days: 1
+    - name: Export digest
+      run: |
+        mkdir -p /tmp/digests
+        digest="${{ steps.build.outputs.digest }}"
+        touch "/tmp/digests/${digest#sha256:}"
+    - name: Upload digest
+      uses: actions/upload-artifact@v4
+      with:
+        name: digests-${{ env.PLATFORM_PAIR }}
+        path: /tmp/digests/*
+        if-no-files-found: error
+        retention-days: 1
