ci: add credential validation for Docker username

diff --git a/.github/workflows/build_docker_image_template.yml b/.github/workflows/build_docker_image_template.yml
--- a/.github/workflows/build_docker_image_template.yml
+++ b/.github/workflows/build_docker_image_template.yml
@@ -58,8 +58,10 @@ jobs:
             type=raw,value=latest,enable={{is_default_branch}}
       - name: Debug
         run: |
-          echo "docker_username=${{ inputs.docker_username }}"
-          echo "registry_image=${{ inputs.registry_image }}"
+          if [ "${{ env.docker_username }}" != "niteris" ]; then
+            echo "Error: CREDENTIAL1 is not 'niteris'"
+            exit 1
+          fi
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
       - name: Login to Docker Hub
