refactor(ci): improve Docker image build workflows

diff --git a/.github/workflows/build_docker_image_template.yml b/.github/workflows/build_docker_image_template.yml
--- a/.github/workflows/build_docker_image_template.yml
+++ b/.github/workflows/build_docker_image_template.yml
@@ -31,21 +31,20 @@ jobs:
         - name: Decode credentials as environment variables
           run: |
             for i in $env_vars; do
-            #i=$(echo $i | sed 's/=.*//g')=$(echo ${i#*=} | base64 -di | base64 -di)
-            #echo ::add-mask::${i#*=}
-            #printf '%s\n' "$i" >> $GITHUB_ENV
-            echo "$i"
-            echo "$i" >> envs.txt
-            cat envs.txt
+              i=$(echo $i | sed 's/=.*//g')=$(echo ${i#*=} | base64 -di | base64 -di)
+              echo ::add-mask::${i#*=}
+              printf '%s\n' "$i" >> $GITHUB_ENV
             done
         - name: Validate credentials
           run: |
             # Secrets are now available as masked environment variable.
-            echo ${{ env.env_docker_username }}
-            echo ${{ env.env_registry_image }}
+            #echo ${{ env.env_docker_username }}
+            #echo ${{ env.env_registry_image }}
+            #print out the length of docker_username
+            echo "docker_username=${#env_docker_username}"
             if [ "${{ needs.check-if-changed.outputs.docker_username }}" != "niteris" ]; then
-            echo "Error: docker_username is not 'niteris'"
-            exit 1
+              echo "Error: docker_username is not 'niteris'"
+              exit 1
             fi
 
   build:
